# Gives the ClusterIP the env=production selector
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  namespace: default

spec:
  selector:
    env: production

---

# Enables the production hostname to the load balancer
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-k8s
  namespace: default

spec:
  rules:
  - host: app.ranchertest.orthoanalytics.biz
    http:
      paths:
      - backend:
          serviceName: hello-k8s
          servicePort: 80
        path: /
        pathType: Prefix
