# IP service for ingress directing
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-k8s

---

# Ingress to service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-k8s
  namespace: default

spec:
  rules:
    # Hostname configured in update_service.yaml files within each overlay
